name: my_likndin_website
description: "A new Flutter project."
 
 
publish_to: 'none'  

 
 
 
 
 
 
 
 
 
 
 
 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

 
 
 
 
 
 
dependencies:
  flutter:
    sdk: flutter

   
   
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.9.1
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/application.png"
  android: true
  ios: true

 
flutter:
  assets:
    - assets/images/
    - assets/cv/

  fonts:
    - family: Cardo
      fonts:
        -  asset: assets/fonts/Cardo-Italic.ttf
           weight: 700 

   
   
   
  uses-material-design: true

   
   
   
   

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
